name: syncToGitee
on:
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          account_type: org
          src: 'github/OBKoro1'
          dst: 'gitee/OBKoro1'
          # dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # gitee_id_rsa.pub 文件
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY_rsa_pub }}
          # gitee_id_rsa 文件
          # dst_key: ${{ secrets.GITEE_PRIVATE_KEY_rsa }}
          # Github rsa文件
          # dst_key: ${{ secrets.PRIVATE_KEY_RSA_GITHUB }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          force_update: true
          debug: true
          static_list: "stop-mess-around-docs"

      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 注意替换为你的 Gitee 用户名1
      #     gitee-username: OBKoro1
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: OBKoro1/stop-mess-around-docs
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: gh-pages